src/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name="blog"),
    path('add/', views.PostCreateView.as_view(), name="post_create"),
    path('<slug:slug>/', views.PostDetailView.as_view(), name="post_detail"),
    path('<slug:slug>/update/', views.PostUpdateView.as_view(), name="post_update"),
    path('<slug:slug>/delete/', views.PostDeleteView.as_view(), name="post_delete"),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('pages.urls')),
    path('blog/', include('blog.urls')),
    path('wedding/', include('wedding.urls')),
    path('admin/', admin.site.urls, name='admin'),
]

src/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
]

src/templates/partials/_contact_form.html
<!--
    Contacts Form
-->
<div class="content contacts-form">
    <div class="row">
        <div class="col col-m-12 col-t-12 col-d-12 col-d-lg-12">

            <!-- title -->
            <div class="title"><span>Contact</span> Form</div>

        </div>
    </div>
    <div class="row">
        <div class="col col-m-12 col-t-12 col-d-12 col-d-lg-12">

            <!-- form -->
            <div class="contact_form card-box">
                <form id="cform" method="post">
                    <div class="row">
                        <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">
                            <div class="group-val">
                                <input type="text" name="name" placeholder="Full Name" />
                            </div>
                        </div>
                        <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">
                            <div class="group-val">
                                <input type="text" name="email" placeholder="Email Address" />
                            </div>
                        </div>
                        <div class="col col-m-12 col-t-12 col-d-12 col-d-lg-12">
                            <div class="group-val">
                                <textarea name="message" placeholder="Your Message"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="align-left">
                        <a href="#" class="button" onclick="$('#cform').submit(); return false;">
                            <span class="text">Send Message</span>
                            <span class="icon"><i class="la la-arrow-right"></i></span>
                        </a>
                    </div>
                </form>
                <div class="alert-success">
                    <p>Thanks, your message is sent successfully.</p>
                </div>
            </div>

        </div>
    </div>
</div>

src/templates/partials/_contacts.html
<!--
    Contacts Info
-->
<div class="content contacts-info">
    <div class="row">
        <div class="col col-m-12 col-t-12 col-d-12 col-d-lg-12">

            <!-- title -->
            <div class="title"><span>Get</span> in Touch</div>

        </div>
    </div>

    <!-- contacts items -->
    <div class="row contacts-items">

        <!-- contacts item -->
        <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">
            <div class="contacts-item card-box">
                <div class="icon"><i class="la la-map-marker"></i></div>
                <div class="name">Address</div>
                <p>
                    France, Paris.
                </p>
            </div>
        </div>

        <!-- contacts item -->
        <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">
            <div class="contacts-item card-box">
                <div class="icon"><i class="la la-at"></i></div>
                <div class="name">Email</div>
                <p>
                    adlard@example.com
                </p>
            </div>
        </div>

        <!-- contacts item -->
        <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">
            <div class="contacts-item card-box">
                <div class="icon"><i class="la la-phone"></i></div>
                <div class="name">Phone</div>
                <p>
                    +123 654 78900
                </p>
            </div>
        </div>

        <!-- contacts item -->
        <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">
            <div class="contacts-item card-box">
                <div class="icon"><i class="la la-check-square"></i></div>
                <div class="name">Freelance</div>
                <p>
                    Available
                </p>
            </div>
        </div>

    </div>

</div>

src/templates/partials/_downloader.html
<div class="circle-bts">
    {% for downloader in page.downloader.all %}
        <a target="_blank" href="{{ downloader.file.url }}"><span><i class="icon {{ downloader.icon.code }}"></i>{{ downloader.button_name }}</span></a>
        {% for social in downloader.social_links.all %}
            <a target="_blank" href="{{ social.url }}"><i class="icon {{ social.icon.code }}"></i></a>
        {% endfor %}
    {% endfor %}
</div>

src/templates/partials/_header.html
<header class="header">

    <!-- logo -->
    <div class="logo">
        <a href="{% url 'pages:index' %}"><span>{{ settings.logo }}</span></a>
    </div>
    
    <!-- menu -->
    <div class="top-menu">
        <ul>
            {% if pages %}
                {% for page in pages %}
                    <li>
                        <a href="#{{ page.route }}">
                            <span class="icon {{ page.icon.code }}"></span>
                            <span class="link">{{ page.name }}</span>
                        </a>
                    </li>
                {% endfor %}
            {% endif %}
        </ul>
    </div>

    <!-- Started socials -->
    <div class="social">
        {% for social in settings.social_on_header.all %}
            <a target="_blank" href="{{ social.url }}"><span class="icon {{ social.icon.code }}"></span></a>
        {% endfor %}
    </div>

    <!-- Mobile Menu -->
    <span class="menu-btn">
        <span class="m-line"></span>
    </span>

</header>

src/templates/partials/_preloader.html
<div class="preloader">
    <div class="centrize full-width">
        <div class="vertical-center">
            <div class="spinner">
                <div class="double-bounce1"></div>
                <div class="double-bounce2"></div>
            </div>
        </div>
    </div>
</div>

src/templates/partials/_side.html
{% if page.side == 'image' %}
    <!-- Image -->
    <div class="card-image col col-m-12 col-t-12 col-d-4 col-d-lg-6" style="background-image: url({{ page.side_image.image.url }});"></div>

{% elif page.side == 'map' %}
    <!-- Map -->
    <div class="card-image col col-m-12 col-t-12 col-d-4 col-d-lg-6">
        <div class="map" id="map"></div>
    </div>
{% endif %}

src/templates/partials/_text.html
<div class="text">
    <p>
        {{ page.text|safe }}
    </p>
</div>

src/templates/partials/_title.html
<div class="title-bg">
    {{ page.background_title }}
</div>

src/templates/partials/_top.html
<!--
    Inner Top
-->
<div class="content inner-top">
    <div class="row">
        {% include 'partials/_title.html' %}
    </div>
</div>


<div class="content inner-top">
    <div class="row">
        <div class="col col-m-12 col-t-12 col-d-12 col-d-lg-12">
            {% include 'partials/_text.html' %}

            {% include 'partials/_downloader.html' %}
        </div>
    </div>
</div>