src/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name="blog"),
    path('add/', views.PostCreateView.as_view(), name="post_create"),
    path('<slug:slug>/', views.PostDetailView.as_view(), name="post_detail"),
    path('<slug:slug>/update/', views.PostUpdateView.as_view(), name="post_update"),
    path('<slug:slug>/delete/', views.PostDeleteView.as_view(), name="post_delete"),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('pages.urls')),
    path('blog/', include('blog.urls')),
    path('wedding/', include('wedding.urls')),
    path('admin/', admin.site.urls, name='admin'),
]

src/blog/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext as _


User = settings.AUTH_USER_MODEL

def upload_location(object, filename):
	return f'{object.author}/{object.slug}_{filename}'



class Post(models.Model):
	subject			= models.CharField(_("Subject"), max_length=50)
	description		= models.TextField(_("Description"))
	author			= models.ForeignKey("Author", verbose_name=_("Author"), on_delete=models.CASCADE)
	image			= models.ImageField(_("Image"), upload_to=upload_location, height_field='height_field', width_field='width_field', blank=True)
	height_field	= models.IntegerField(_("Height"), null=True)
	width_field		= models.IntegerField(_("Width"), null=True)
	category		= models.ForeignKey("Category", verbose_name=_("Category"), on_delete=models.CASCADE)
	slug			= models.SlugField(_("Slug"), max_length=50, unique=True)
	publish_date	= models.DateTimeField(_("Publish Date"), auto_now_add=True)
	last_modify		= models.DateTimeField(_("Last Modify"), auto_now=True)
	hide			= models.BooleanField(_("Hide"))
	
	class Meta:
		verbose_name        = _("Post")
		verbose_name_plural = _("Posts")

	def __str__(self):
		return self.subject

	def get_absolute_url(self):
		return reverse("blog:post_detail", kwargs={"slug": self.slug})



class Category(models.Model):
	category = models.CharField(_("Category"), max_length=50)
	
	class Meta:
		verbose_name        = _("Category")
		verbose_name_plural = _("Categories")

	def __str__(self):
		return self.category



class Author(models.Model):
	user	= models.ForeignKey(User, verbose_name=_("User"), on_delete=models.CASCADE)
	email	= models.EmailField(_("Email"))
	phone	= models.CharField(_("Phone"), max_length=50, blank=True, help_text='Contact Phone Number')
	
	class Meta:
		verbose_name        = _("Author")
		verbose_name_plural = _("Authors")

	def __str__(self):
		return self.user.username

src/blog/forms.py
from django import forms
from .models import Post


class PostModelForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['category', 'subject', 'description', 'image']

src/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Author
from .forms import PostModelForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils import timezone
from django.template.defaultfilters import slugify


class PostListView(ListView):
    queryset = Post.objects.filter(hide=False)



class PostDetailView(DetailView):
    queryset = Post.objects.filter(hide=False)



class PostCreateView(CreateView):
    template_name = 'blog/post_create.html'
    form_class = PostModelForm
    queryset = Post.objects.all()


    def form_valid(self, form):
        """
        This method is called when valid form data has been POSTed.
        It should return an HttpResponse.
        """
        form.instance.author, created = Author.objects.get_or_create(user=self.request.user)
        form.instance.slug = slugify(form.cleaned_data['subject'])
        form.instance.publish_date = timezone.now
        return super().form_valid(form)



class PostUpdateView(UpdateView):
    template_name = 'blog/post_update.html'
    form_class = PostModelForm

    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Post, slug=slug, hide=False)

    def form_valid(self, form):
        form.instance.last_modify = timezone.now
        return super().form_valid(form)


class PostDeleteView(DeleteView):
    template_name = 'blog/post_delete.html'

    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Post, slug=slug, hide=False)

    def get_success_url(self):
        return '../../'

src/templates/old/_blog.html
{% load static %}

<div class="card-inner" id="{{ page.route }}">
    <div class="row card-container">
            
        <!--
            Card Wrap
        -->
        <div class="card-wrap col col-m-12 col-t-12 col-d-8 col-d-lg-6" data-simplebar>
            
            <!-- Blog Image -->
            <div class="card-image col col-m-12 col-t-12 col-d-4 col-d-lg-6" style="background-image: url({% static 'images/profile4.jpg' %});"></div>
            
            <!--
                Inner Top
            -->
            <div class="content inner-top">
                <div class="row">
                    <div class="col col-m-12 col-t-12 col-d-12 col-d-lg-12">
                        <div class="title-bg">My Blog</div>
                    </div>
                </div>
            </div>

            <!--
                Blog
            -->
            <div class="content blog">
                <div class="row">
                    <div class="col col-m-12 col-t-5 col-d-5 col-d-lg-5">

                        <!-- title -->
                        <div class="title"><span>My</span> Blog</div>

                    </div>
                    <div class="col col-m-12 col-t-7 col-d-7 col-d-lg-7">

                        <!-- filters -->
                        <div class="all-blog">
                            <a href="{% url 'blog:blog' %}">All Blog</a>
                        </div>

                    </div>
                </div>

                <!-- blog items -->
                <div class="row">

                    <!-- blog item -->
                    {% for instance in object_list %}
                    <div class="col col-m-12 col-t-12 col-d-12 col-d-lg-12">
                        <div class="box-item card-box">
                            <div class="image">
                                <a href="{{ instance.get_absolute_url }}">
                                    <img src="{% static 'images/blog/blog1.jpg' %}" alt="" />
                                    <span class="info">
                                        <span class="icon la la-newspaper-o"></span>
                                    </span>
                                    <span class="date"><strong>20</strong>Jun</span>
                                </a>
                            </div>
                            <div class="desc">
                                <a href="blog-post.html" class="name">{{ instance }}</a>
                                <div class="category">{{ instance.category }}</div>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <p>There are no posts</p>
                    {% endfor %}

                </div>

            </div> 

        </div>
            
    </div>
</div>

src/templates/old/_contacts.html
{% load static %}

<div class="card-inner" id="{{ page.route }}">
    <div class="row card-container">
        
        <!--
            Card Wrap
        -->
        <div class="card-wrap col col-m-12 col-t-12 col-d-8 col-d-lg-6" data-simplebar>
            
            <!-- Map -->
            <div class="card-image col col-m-12 col-t-12 col-d-4 col-d-lg-6">
                <div class="map" id="map"></div>
            </div>
                
            <!--
                Inner Top
            -->
            <div class="content inner-top">
                <div class="row">
                    <div class="col col-m-12 col-t-12 col-d-12 col-d-lg-12">
                        <div class="title-bg">Contacts</div>
                    </div>
                </div>
            </div>

            <!--
                Contacts Info
            -->
            <div class="content contacts-info">
                <div class="row">
                    <div class="col col-m-12 col-t-12 col-d-12 col-d-lg-12">

                        <!-- title -->
                        <div class="title"><span>Get</span> in Touch</div>

                    </div>
                </div>

                <!-- contacts items -->
                <div class="row contacts-items">

                    <!-- contacts item -->
                    <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">
                        <div class="contacts-item card-box">
                            <div class="icon"><i class="la la-map-marker"></i></div>
                            <div class="name">Address</div>
                            <p>
                                France, Paris.
                            </p>
                        </div>
                    </div>

                    <!-- contacts item -->
                    <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">
                        <div class="contacts-item card-box">
                            <div class="icon"><i class="la la-at"></i></div>
                            <div class="name">Email</div>
                            <p>
                                adlard@example.com
                            </p>
                        </div>
                    </div>

                    <!-- contacts item -->
                    <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">
                        <div class="contacts-item card-box">
                            <div class="icon"><i class="la la-phone"></i></div>
                            <div class="name">Phone</div>
                            <p>
                                +123 654 78900
                            </p>
                        </div>
                    </div>

                    <!-- contacts item -->
                    <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">
                        <div class="contacts-item card-box">
                            <div class="icon"><i class="la la-check-square"></i></div>
                            <div class="name">Freelance</div>
                            <p>
                                Available
                            </p>
                        </div>
                    </div>

                </div>

            </div>

            <!--
                Contacts Form
            -->
            <div class="content contacts-form">
                <div class="row">
                    <div class="col col-m-12 col-t-12 col-d-12 col-d-lg-12">

                        <!-- title -->
                        <div class="title"><span>Contact</span> Form</div>

                    </div>
                </div>
                <div class="row">
                    <div class="col col-m-12 col-t-12 col-d-12 col-d-lg-12">

                        <!-- form -->
                        <div class="contact_form card-box">
                            <form id="cform" method="post">
                                <div class="row">
                                    <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">
                                        <div class="group-val">
                                            <input type="text" name="name" placeholder="Full Name" />
                                        </div>
                                    </div>
                                    <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">
                                        <div class="group-val">
                                            <input type="text" name="email" placeholder="Email Address" />
                                        </div>
                                    </div>
                                    <div class="col col-m-12 col-t-12 col-d-12 col-d-lg-12">
                                        <div class="group-val">
                                            <textarea name="message" placeholder="Your Message"></textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="align-left">
                                    <a href="#" class="button" onclick="$('#cform').submit(); return false;">
                                        <span class="text">Send Message</span>
                                        <span class="icon"><i class="la la-arrow-right"></i></span>
                                    </a>
                                </div>
                            </form>
                            <div class="alert-success">
                                <p>Thanks, your message is sent successfully.</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
        
    </div>
</div>

src/templates/old/_resume.html
{% load static %}

<div class="card-inner" id="{{ page.route }}">
    <div class="row card-container">
            
        <!--
            Card Wrap
        -->
        <div class="card-wrap col col-m-12 col-t-12 col-d-8 col-d-lg-6" data-simplebar>

            <!-- Resume Image -->
            <div class="card-image col col-m-12 col-t-12 col-d-4 col-d-lg-6" style="background-image: url({% static 'images/profile2.jpg' %});"></div>

            <!--
                Inner Top
            -->
            <div class="content inner-top">
                <div class="row">
                    <div class="col col-m-12 col-t-12 col-d-12 col-d-lg-12">
                        <div class="title-bg">Resume</div>
                    </div>
                </div>
            </div>

            <!--
                Resume
            -->
            <div class="content resume">
                <div class="row">
                    <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">

                        <!-- title -->
                        <div class="title"><span>My</span> Experience</div>

                        <!-- resume items -->
                        <div class="resume-items card-box">

                            <!-- resume item -->
                            <div class="resume-item">
                                <div class="name">Web Development</div>
                                <div class="date">2013-Present <span>|</span> Facebook Inc.</div>
                                <p>
                                    Collaborate with creative and development teams on the execution of ideas.
                                </p>
                            </div>

                            <!-- resume item -->
                            <div class="resume-item">
                                <div class="name">Front-end Developer</div>
                                <div class="date">2011-2012 <span>|</span> Google Inc.</div>
                                <p>
                                    Monitored technical aspects of the front-end delivery for several projects.
                                </p>
                            </div>

                            <!-- resume item -->
                            <div class="resume-item">
                                <div class="name">Senior Developer</div>
                                <div class="date">2009-2010 <span>|</span> Abc Inc.</div>
                                <p>
                                    Optimize website performance using latest technology.
                                </p>
                            </div>

                        </div>
                    </div>
                    <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">

                        <!-- title -->
                        <div class="title"><span>My</span> Education</div>

                        <!-- resume items -->
                        <div class="resume-items card-box">

                            <!-- resume item -->
                            <div class="resume-item">
                                <div class="name">Art University</div>
                                <div class="date">2006-2008 <span>|</span> New York</div>
                                <p>
                                    Bachelor's Degree in Computer Science ABC Technical Institute, Jefferson, Missouri
                                </p>
                            </div>

                            <!-- resume item -->
                            <div class="resume-item">
                                <div class="name">Programming Course</div>
                                <div class="date">2005-2006 <span>|</span> Paris</div>
                                <p>
                                    Bachelor's Degree in Computer Science ABC Technical Institute, Jefferson, Missouri
                                </p>
                            </div>

                            <!-- resume item -->
                            <div class="resume-item">
                                <div class="name">Web Design Course</div>
                                <div class="date">2004-2005 <span>|</span> London</div>
                                <p>
                                    Converted Photoshop layouts to web pages using HTML, CSS, and JavaScript
                                </p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <!--
                Skills
            -->
            <div class="content skills">
                <div class="row">
                    <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">

                        <!-- title -->
                        <div class="title"><span>Personal</span> Skills</div>

                        <!-- skills -->
                        <div class="skills-list card-box">
                            <ul>
                                <li> 
                                    <div class="name">Communication</div>
                                    <div class="progress">
                                        <div class="percentage" style="width:90%;"></div>
                                    </div>
                                </li>
                                <li> 
                                    <div class="name">Team Work</div>
                                    <div class="progress">
                                        <div class="percentage" style="width:65%;"></div>
                                    </div>
                                </li>
                                <li> 
                                    <div class="name">Leadership</div>
                                    <div class="progress">
                                        <div class="percentage" style="width:75%;"></div>
                                    </div>
                                </li>
                                <li>
                                    <div class="name">Language</div>
                                    <div class="progress">
                                        <div class="percentage" style="width:85%;"></div>
                                    </div>
                                </li>
                            </ul>
                        </div>

                    </div>
                    <div class="col col-m-12 col-t-6 col-d-6 col-d-lg-6">

                        <!-- title -->
                        <div class="title"><span>Professional</span> Skills</div>

                        <!-- skills -->
                        <div class="skills-list card-box">
                            <ul>
                                <li> 
                                    <div class="name">WordPress</div>
                                    <div class="progress">
                                        <div class="percentage" style="width:90%;"></div>
                                    </div>
                                </li>
                                <li> 
                                    <div class="name">PHP / MYSQL</div>
                                    <div class="progress">
                                        <div class="percentage" style="width:65%;"></div>
                                    </div>
                                </li>
                                <li> 
                                    <div class="name">HTML / CSS / JS</div>
                                    <div class="progress">
                                        <div class="percentage" style="width:95%;"></div>
                                    </div>
                                </li>
                                <li>
                                    <div class="name">Photoshop</div>
                                    <div class="progress">
                                        <div class="percentage" style="width:85%;"></div>
                                    </div>
                                </li>
                            </ul>
                        </div>

                    </div>
                </div>
            </div>

        </div>
        
    </div>
</div>